apiVersion: v1
kind: Service
metadata:
  name: usermanagement
spec:
 type: NodePort
 ports:
  - protocol: TCP
    targetPort: 5000
    port: 5000
 selector:
  app: usermanagement
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-deployment
spec:
  selector:
    matchLabels:
      app: usermanagement
  replicas: 2
  template:
    metadata:
      labels:
        app: usermanagement
    spec:
      containers:
      - name: usermanagement
        imagePullPolicy: Always
        image: nayeemullahbaig/noodle/user-image:latest
        ports:
        - containerPort: 5000