node{
    
    stage("Git Clone")
    {
        git branch: 'integration', credentialsId: 'GIT_CREDENTIALS', url: 'https://github.com/airavata-courses/Noodle.git'
    }
	stage('Testing Session Service') {
                        
                sh '''
       
                    sudo apt --assume-yes install maven
                    cd "sessionmanagement"
                    mvn pre-clean
                    mvn compile
                    mvn package
                    
                    '''             
    
    }  
    stage('Building Docker Image')
    {
			sh "docker-compose build"
              
    }
    stage('Pushing to Docker hub') 
    {
        withCredentials([string(credentialsId: 'DOCKER_HUB_CREDENTIALS', variable: 'DOCKER_HUB_CREDENTIALS')]) {
            sh "docker login docker.io -u nayeemullahbaig -p ${DOCKER_HUB_CREDENTIALS}"
           
        }
             
             sh "docker-compose push"
            
    }
	stage('Deploy app in K8s')
    {
       
        kubernetesDeploy(
            configs: 'kubedeploy/messaging.yaml', 
            kubeconfigId: 'KUBERNETES_CLUSTER_CONFIG',
            enableConfigSubstitution: true
        )
        kubernetesDeploy(
            configs: 'kubedeploy/data-retrieveal.yaml', 
            kubeconfigId: 'KUBERNETES_CLUSTER_CONFIG',
            enableConfigSubstitution: true
        )
        kubernetesDeploy(
            configs: 'kubedeploy/data-processing.yaml', 
            kubeconfigId: 'KUBERNETES_CLUSTER_CONFIG',
            enableConfigSubstitution: true
        )
        kubernetesDeploy(
            configs: 'kubedeploy/data-modelling.yaml', 
            kubeconfigId: 'KUBERNETES_CLUSTER_CONFIG',
            enableConfigSubstitution: true
        )
        kubernetesDeploy(
            configs: 'kubedeploy/session-management.yaml', 
            kubeconfigId: 'KUBERNETES_CLUSTER_CONFIG',
            enableConfigSubstitution: true
        )
        kubernetesDeploy(
            configs: 'kubedeploy/usermanagement.yaml', 
            kubeconfigId: 'KUBERNETES_CLUSTER_CONFIG',
            enableConfigSubstitution: true
        )
        kubernetesDeploy(
            configs: 'kubedeploy/apigateway.yaml', 
            kubeconfigId: 'KUBERNETES_CLUSTER_CONFIG',
            enableConfigSubstitution: true
        )
         kubernetesDeploy(
            configs: 'kubedeploy/frontend.yaml', 
            kubeconfigId: 'KUBERNETES_CLUSTER_CONFIG',
            enableConfigSubstitution: true
        )
        
    }    
    
}