apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
  selector:
    app: apigateway
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: nayeemullahbaig/apigateway-image
        ports:
        - containerPort: 5050
        env:
          - name: KAFKA_SERVER
            value: kafka-service:9092