apiVersion: v1
kind: Service
metadata:
  name: mdb
spec:
  ports:
  - protocol: TCP
    port: 5435
    targetPort: 5432
  selector:
    app: mdb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdb-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdb
  template:
    metadata:
      labels:
        app: mdb
    spec:
      containers:
      - name: mdb
        image: postgres:12
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: modeldb
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: idontknow.3

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-model-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-model
  template:
    metadata:
      labels:
        app: data-model
    spec:
      containers:
      - name: model-image
        image: nayeemullahbaig/model-image
        env:
          - name: SQLALCHEMY_DATABASE_URI
            value: postgresql://postgres:idontknow.3@mdb/modeldb
          - name: KAFKA_SERVER
            value: kafka-serivce:9092