apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: frontend
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
      - name: frontend-image
        image: nayeemullahbaig/frontend-image
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: API_GATEWAY
          value: apigateway-service:5050
        - name: REACT_APP_USER_SERVICE
          value: http://user-service:5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: v2
    spec:
      containers:
      - name: frontend-image
        image: nayeemullahbaig/frontend-image:0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: API_GATEWAY
          value: apigateway-service:5050
        - name: REACT_APP_USER_SERVICE
          value: http://user-service:5000

