apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 5006
    targetPort: 5006
  selector:
    app: frontend
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-image
        image: nayeemullahbaig/frontend-image
        ports:
        - containerPort: 5006