apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apigateway-service
spec:
  hosts:
  - "*"
  gateways:
  - noodle-gateway
  http:
  - route:
    - destination:
        host: apigateway-service
        
---


apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-service
spec:
  hosts:
  - "*"
  gateways:
  - noodle-gateway
  http:
  - route:
    - destination:
        host: frontend-service
        
---


apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: session-service
spec:
  hosts:
  - "*"
  gateways:
  - noodle-gateway
  http:
  - route:
    - destination:
        host: session-service
        
        
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-service
spec:
  hosts:
  - "*"
  gateways:
  - noodle-gateway
  http:
  - route:
    - destination:
        host: user-service
        
        