apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
 type: NodePort
 ports:
  - protocol: TCP
    targetPort: 5000
    port: 5000
    nodePort: 30001
 selector:
  app: usermanagement
  
---

apiVersion: v1
kind: Service
metadata:
  name: udb
spec:
 type: NodePort
 ports:
  - protocol: TCP
    targetPort: 27017
    port: 27017
 selector:
  app: udb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: userman-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udb
      version: v1
  template:
    metadata:
      labels:
        app: udb
        version: v1

    spec:
      containers:
      - name: udb
        image: mongo:4.0.4
        ports:
        - containerPort: 27017
        
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-deployment
spec:
  selector:
    matchLabels:
      app: usermanagement
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: usermanagement
        version: v1
    spec:
      containers:
      - name: user-image
        imagePullPolicy: Always
        image: nayeemullahbaig/user-image
        ports:
        - containerPort: 5000
        env:
        - name: mongoURI
          value: mongodb://udb/ADS
          
          
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-deployment
spec:
  selector:
    matchLabels:
      app: usermanagement
      version: v2
  replicas: 1
  template:
    metadata:
      labels:
        app: usermanagement
        version: v2
    spec:
      containers:
      - name: user-image
        imagePullPolicy: Always
        image: nayeemullahbaig/user-image:0.2
        ports:
        - containerPort: 5000
        env:
        - name: mongoURI
          value: mongodb://udb/ADS